# Generated by Django 3.0.3 on 2020-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageFilter', '0002_auto_20200306_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='getimage',
            name='kindOfTool',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='getimage',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='getimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
