# Generated by Django 3.0.3 on 2020-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageFilter', '0004_auto_20200310_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='numberOfColors',
            field=models.IntegerField(default=0),
        ),
    ]
