# Generated by Django 3.0.3 on 2020-03-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageFilter', '0006_auto_20200313_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
